

#ifndef  STM32_ADVANCED_TIMER_H
#define  STM32_ADVANCED_TIMER_H

#include  <stdint.h>
#include  "util.h"

enum {
    AD_TIMER_DTS = 0,
    AD_TIMER_DTS2,
    AD_TIMER_DTS4,
    AD_TIMER_DTS_MAX  =  AD_TIMER_DTS4,
};

enum {
    AD_TIMER_EDGE_ALIGNED  =  0,
    AD_TIMER_CENTER_ALIGNED1,
    AD_TIMER_CENTER_ALIGNED2,
    AD_TIMER_CENTER_ALIGNED3,
    AD_TIMER_CENTER_ALIGNED_MAX =  AD_TIMER_CENTER_ALIGNED3,
};


enum  {
    AD_TIMER_MASTER_RESET = 0,
    AD_TIMER_MASTER_ENABLE,
    AD_TIMER_MASTER_UPDATE,
    AD_TIMER_MASTER_COMPARE_PULSE,
    AD_TIMER_MASTER_COMPARE_OC1REF,
    AD_TIMER_MASTER_COMPARE_OC2REF,
    AD_TIMER_MASTER_COMPARE_OC3REF,
    AD_TIMER_MASTER_COMPARE_OC4REF,
    AD_TIMER_MAX_MASTER_MODE  =   AD_TIMER_MASTER_COMPARE_OC4REF,
};
enum  {
    EXTERNAL_TRIGGER_PRESCALER_OFF  = 0,
    EXTERNAL_TRIGGER_PRESCALER2,
    EXTERNAL_TRIGGER_PRESCALER4,
    EXTERNAL_TRIGGER_PRESCALER8,

};


enum {
    AD_TIMER_INTERNAL_TRIGGER0  =  0,
    AD_TIMER_INTERNAL_TRIGGER1,
    AD_TIMER_INTERNAL_TRIGGER2,
    AD_TIMER_INTERNAL_TRIGGER3,
    AD_TIMER_TI1_EDGE_DETECTOR,
    AD_TIMER_FILTERED_TIMER_INPUT1,
    AD_TIMER_FILTERED_TIMER_INPUT2,
    AD_TIMER_EXTERNAL_TRIGGER_INPUT,
    
};


enum  {
    AD_TIMER_SLAVE_MODE_DISABLED  =  0,
    AD_TIMER_SLAVE_ENCODER_MODE1,
    AD_TIMER_SLAVE_ENCODER_MODE2,
    AD_TIMER_SLAVE_ENCODER_MODE3,
    AD_TIMER_SLAVE_RESET_MODE,
    AD_TIMER_SLAVE_GATED_MODE,
    AD_TIMER_SLAVE_TRIGGER_MODE,
    AD_TIMER_SLAVE_EXTERNAL_CLOCK_MODE1,


};








#endif

