

#ifndef  STM32_ADVANCED_TIMER_H
#define  STM32_ADVANCED_TIMER_H

#include  <stdint.h>
#include  "util.h"

enum {
    AD_TIMER_DTS = 0,
    AD_TIMER_DTS2,
    AD_TIMER_DTS4,
    AD_TIMER_DTS_MAX  =  AD_TIMER_DTS4,
};

enum {
    AD_TIMER_EDGE_ALIGNED  =  0,
    AD_TIMER_CENTER_ALIGNED1,
    AD_TIMER_CENTER_ALIGNED2,
    AD_TIMER_CENTER_ALIGNED3,
    AD_TIMER_CENTER_ALIGNED_MAX =  AD_TIMER_CENTER_ALIGNED3,
};


enum  {
    AD_TIMER_MASTER_RESET = 0,
    AD_TIMER_MASTER_ENABLE,
    AD_TIMER_MASTER_UPDATE,
    AD_TIMER_MASTER_COMPARE_PULSE,
    AD_TIMER_MASTER_COMPARE_OC1REF,
    AD_TIMER_MASTER_COMPARE_OC2REF,
    AD_TIMER_MASTER_COMPARE_OC3REF,
    AD_TIMER_MASTER_COMPARE_OC4REF,
    AD_TIMER_MAX_MASTER_MODE  =   AD_TIMER_MASTER_COMPARE_OC4REF,
};






#endif

